apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: faloladare-multi-com-tls
spec:
  secretName: faloladare-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: faloladare.com.ng
  dnsNames:
    - faloladare.com.ng
    - www.faloladare.com.ng
  acme:
    config:
      - http01:
          ingressClass: nginx
      domains:
        - faloladare.com.ng
        - www.faloladare.com.ng