apiVersion: networking.k8s.io/v1beta1
kind: Ingress #kind of object
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx #create ingress controller based on nginx project
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1 #rewrite url to /
spec:
  rules:
    - http:
        paths:
          - path: /?(.*) #send requests to any path that starts with / or ff by /* and not /api
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)  #send requests to any path that starts with /api or ff by /api*
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000